package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseAccounts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accounts extends BaseAccounts<Accounts> {
	
}
