package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseCmsProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsProvince extends BaseCmsProvince<CmsProvince> {
	
}
