package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseCmsRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsRegion extends BaseCmsRegion<CmsRegion> {
	
}
