package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseCpuFormat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CpuFormat extends BaseCpuFormat<CpuFormat> {
	
}
