package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseGroupMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupMember extends BaseGroupMember<GroupMember> {
	
}
