package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseNavigation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Navigation extends BaseNavigation<Navigation> {
	
}
