package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	
}
