package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseTbHanrdbase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbHanrdbase extends BaseTbHanrdbase<TbHanrdbase> {
	
}
