package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	
}
