package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseVxBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VxBusiness extends BaseVxBusiness<VxBusiness> {
	
}
