package com.wechat.entity.bean;

import com.wechat.entity.bean.base.BaseWechatGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatGroup extends BaseWechatGroup<WechatGroup> {
	
}
