package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTbHanrdbase<M extends BaseTbHanrdbase<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setIsStop(java.lang.Integer IsStop) {
		set("IsStop", IsStop);
	}
	
	public java.lang.Integer getIsStop() {
		return getInt("IsStop");
	}

	public void setSysBootloadre(java.lang.String sysBootloadre) {
		set("Sys_Bootloadre", sysBootloadre);
	}
	
	public java.lang.String getSysBootloadre() {
		return getStr("Sys_Bootloadre");
	}

	public void setSysBrand(java.lang.String sysBrand) {
		set("Sys_Brand", sysBrand);
	}
	
	public java.lang.String getSysBrand() {
		return getStr("Sys_Brand");
	}

	public void setSysCpuAbi(java.lang.String sysCpuAbi) {
		set("Sys_CPU_ABI", sysCpuAbi);
	}
	
	public java.lang.String getSysCpuAbi() {
		return getStr("Sys_CPU_ABI");
	}

	public void setSysCpuAbi2(java.lang.String sysCpuAbi2) {
		set("Sys_CPU_ABI2", sysCpuAbi2);
	}
	
	public java.lang.String getSysCpuAbi2() {
		return getStr("Sys_CPU_ABI2");
	}

	public void setSysDensitydpi(java.lang.String sysDensitydpi) {
		set("Sys_DensityDpi", sysDensitydpi);
	}
	
	public java.lang.String getSysDensitydpi() {
		return getStr("Sys_DensityDpi");
	}

	public void setSysDevice(java.lang.String sysDevice) {
		set("Sys_Device", sysDevice);
	}
	
	public java.lang.String getSysDevice() {
		return getStr("Sys_Device");
	}

	public void setSysDisplay(java.lang.String sysDisplay) {
		set("Sys_Display", sysDisplay);
	}
	
	public java.lang.String getSysDisplay() {
		return getStr("Sys_Display");
	}

	public void setSysFingerprint(java.lang.String sysFingerprint) {
		set("Sys_Fingerprint", sysFingerprint);
	}
	
	public java.lang.String getSysFingerprint() {
		return getStr("Sys_Fingerprint");
	}

	public void setSysHeightpixels(java.lang.String sysHeightpixels) {
		set("Sys_HeightPixels", sysHeightpixels);
	}
	
	public java.lang.String getSysHeightpixels() {
		return getStr("Sys_HeightPixels");
	}

	public void setSysModel(java.lang.String sysModel) {
		set("Sys_Model", sysModel);
	}
	
	public java.lang.String getSysModel() {
		return getStr("Sys_Model");
	}

	public void setSysManufacturer(java.lang.String sysManufacturer) {
		set("Sys_Manufacturer", sysManufacturer);
	}
	
	public java.lang.String getSysManufacturer() {
		return getStr("Sys_Manufacturer");
	}

	public void setSysRadiover(java.lang.String sysRadiover) {
		set("Sys_RadioVer", sysRadiover);
	}
	
	public java.lang.String getSysRadiover() {
		return getStr("Sys_RadioVer");
	}

	public void setSysSerial(java.lang.String sysSerial) {
		set("Sys_Serial", sysSerial);
	}
	
	public java.lang.String getSysSerial() {
		return getStr("Sys_Serial");
	}

	public void setSysVerIncrease(java.lang.String sysVerIncrease) {
		set("Sys_Ver_Increase", sysVerIncrease);
	}
	
	public java.lang.String getSysVerIncrease() {
		return getStr("Sys_Ver_Increase");
	}

	public void setSysVerRelease(java.lang.String sysVerRelease) {
		set("Sys_Ver_Release", sysVerRelease);
	}
	
	public java.lang.String getSysVerRelease() {
		return getStr("Sys_Ver_Release");
	}

	public void setSysVerSdkint(java.lang.String sysVerSdkint) {
		set("Sys_Ver_SdkInt", sysVerSdkint);
	}
	
	public java.lang.String getSysVerSdkint() {
		return getStr("Sys_Ver_SdkInt");
	}

	public void setSysWidthpixels(java.lang.String sysWidthpixels) {
		set("Sys_WidthPixels", sysWidthpixels);
	}
	
	public java.lang.String getSysWidthpixels() {
		return getStr("Sys_WidthPixels");
	}

	public void setCpuArchitecture(java.lang.String cpuArchitecture) {
		set("CPU_architecture", cpuArchitecture);
	}
	
	public java.lang.String getCpuArchitecture() {
		return getStr("CPU_architecture");
	}

	public void setCpuCpucores(java.lang.String cpuCpucores) {
		set("Cpu_CPUCores", cpuCpucores);
	}
	
	public java.lang.String getCpuCpucores() {
		return getStr("Cpu_CPUCores");
	}

	public void setCpuHardware(java.lang.String cpuHardware) {
		set("Cpu_Hardware", cpuHardware);
	}
	
	public java.lang.String getCpuHardware() {
		return getStr("Cpu_Hardware");
	}

	public void setSysBoard(java.lang.String sysBoard) {
		set("Sys_Board", sysBoard);
	}
	
	public java.lang.String getSysBoard() {
		return getStr("Sys_Board");
	}

	public void setCpuFeatures(java.lang.String cpuFeatures) {
		set("Cpu_Features", cpuFeatures);
	}
	
	public java.lang.String getCpuFeatures() {
		return getStr("Cpu_Features");
	}

	public void setCpuModelname(java.lang.String cpuModelname) {
		set("Cpu_ModelName", cpuModelname);
	}
	
	public java.lang.String getCpuModelname() {
		return getStr("Cpu_ModelName");
	}

	public void setCpuVevision(java.lang.String cpuVevision) {
		set("Cpu_Vevision", cpuVevision);
	}
	
	public java.lang.String getCpuVevision() {
		return getStr("Cpu_Vevision");
	}

	public void setCpuSerial(java.lang.String cpuSerial) {
		set("Cpu_Serial", cpuSerial);
	}
	
	public java.lang.String getCpuSerial() {
		return getStr("Cpu_Serial");
	}

	public void setSysImei(java.lang.String sysImei) {
		set("Sys_IMEI", sysImei);
	}
	
	public java.lang.String getSysImei() {
		return getStr("Sys_IMEI");
	}

	public void setSysHardware(java.lang.String sysHardware) {
		set("Sys_Hardware", sysHardware);
	}
	
	public java.lang.String getSysHardware() {
		return getStr("Sys_Hardware");
	}

	public void setSysProduct(java.lang.String sysProduct) {
		set("Sys_Product", sysProduct);
	}
	
	public java.lang.String getSysProduct() {
		return getStr("Sys_Product");
	}

	public void setCpuFormat(java.lang.Long cpuFormat) {
		set("Cpu_Format", cpuFormat);
	}
	
	public java.lang.Long getCpuFormat() {
		return getLong("Cpu_Format");
	}

	public void setSysAndroidid(java.lang.String sysAndroidid) {
		set("Sys_AndroidID", sysAndroidid);
	}
	
	public java.lang.String getSysAndroidid() {
		return getStr("Sys_AndroidID");
	}

}
