package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseState<M extends BaseState<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFatherId(java.lang.Integer fatherId) {
		set("father_id", fatherId);
	}
	
	public java.lang.Integer getFatherId() {
		return getInt("father_id");
	}

	public void setStateTypeCode(java.lang.Integer stateTypeCode) {
		set("state_type_code", stateTypeCode);
	}
	
	public java.lang.Integer getStateTypeCode() {
		return getInt("state_type_code");
	}

	public void setStateMsg(java.lang.String stateMsg) {
		set("state_msg", stateMsg);
	}
	
	public java.lang.String getStateMsg() {
		return getStr("state_msg");
	}

}
