package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupMember<M extends BaseGroupMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setWechatGroupId(java.lang.Integer wechatGroupId) {
		set("wechat_group_id", wechatGroupId);
	}
	
	public java.lang.Integer getWechatGroupId() {
		return getInt("wechat_group_id");
	}

	public void setAccountsId(java.lang.Integer accountsId) {
		set("accounts_id", accountsId);
	}
	
	public java.lang.Integer getAccountsId() {
		return getInt("accounts_id");
	}

	public void setAddGroupTime(java.util.Date addGroupTime) {
		set("add_group_time", addGroupTime);
	}
	
	public java.util.Date getAddGroupTime() {
		return get("add_group_time");
	}

}
