package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCpuFormat<M extends BaseCpuFormat<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCpuRule(java.lang.String cpuRule) {
		set("cpu_rule", cpuRule);
	}
	
	public java.lang.String getCpuRule() {
		return getStr("cpu_rule");
	}

}
