package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWechatGroup<M extends BaseWechatGroup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}

	public void setGroupKey(java.lang.String groupKey) {
		set("group_key", groupKey);
	}
	
	public java.lang.String getGroupKey() {
		return getStr("group_key");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setAddGroupTypeCode(java.lang.Integer addGroupTypeCode) {
		set("add_group_type_code", addGroupTypeCode);
	}
	
	public java.lang.Integer getAddGroupTypeCode() {
		return getInt("add_group_type_code");
	}

	public void setQrcodeUrl(java.lang.String qrcodeUrl) {
		set("QRCode_url", qrcodeUrl);
	}
	
	public java.lang.String getQrcodeUrl() {
		return getStr("QRCode_url");
	}

}
