package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFriend<M extends BaseFriend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAccountsId(java.lang.Integer accountsId) {
		set("accounts_id", accountsId);
	}
	
	public java.lang.Integer getAccountsId() {
		return getInt("accounts_id");
	}

	public void setFriendAccountId(java.lang.Integer friendAccountId) {
		set("friend_account_id", friendAccountId);
	}
	
	public java.lang.Integer getFriendAccountId() {
		return getInt("friend_account_id");
	}

	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}
	
	public java.util.Date getAddTime() {
		return get("add_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setFriendRemark(java.lang.String friendRemark) {
		set("friend_remark", friendRemark);
	}
	
	public java.lang.String getFriendRemark() {
		return getStr("friend_remark");
	}

}
