package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPermissionName(java.lang.String permissionName) {
		set("permission_name", permissionName);
	}
	
	public java.lang.String getPermissionName() {
		return getStr("permission_name");
	}

	public void setPermissionCode(java.lang.Integer permissionCode) {
		set("permission_code", permissionCode);
	}
	
	public java.lang.Integer getPermissionCode() {
		return getInt("permission_code");
	}

	public void setPermissionUrl(java.lang.String permissionUrl) {
		set("permission_url", permissionUrl);
	}
	
	public java.lang.String getPermissionUrl() {
		return getStr("permission_url");
	}

	public void setPermissionRemark(java.lang.String permissionRemark) {
		set("permission_remark", permissionRemark);
	}
	
	public java.lang.String getPermissionRemark() {
		return getStr("permission_remark");
	}

}
