package com.wechat.entity.bean.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVxBusiness<M extends BaseVxBusiness<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBusinessTypeCode(java.lang.Integer businessTypeCode) {
		set("business_type_code", businessTypeCode);
	}
	
	public java.lang.Integer getBusinessTypeCode() {
		return getInt("business_type_code");
	}

	public void setBusinessToAccountId(java.lang.Integer businessToAccountId) {
		set("business_to_account_id", businessToAccountId);
	}
	
	public java.lang.Integer getBusinessToAccountId() {
		return getInt("business_to_account_id");
	}

	public void setBusinessToUserId(java.lang.Integer businessToUserId) {
		set("business_to_user_id", businessToUserId);
	}
	
	public java.lang.Integer getBusinessToUserId() {
		return getInt("business_to_user_id");
	}

	public void setBusinessMsg(java.lang.String businessMsg) {
		set("business_msg", businessMsg);
	}
	
	public java.lang.String getBusinessMsg() {
		return getStr("business_msg");
	}

	public void setBusinessState(java.lang.Integer businessState) {
		set("business_state", businessState);
	}
	
	public java.lang.Integer getBusinessState() {
		return getInt("business_state");
	}

	public void setBusinessResultMsg(java.lang.String businessResultMsg) {
		set("business_result_msg", businessResultMsg);
	}
	
	public java.lang.String getBusinessResultMsg() {
		return getStr("business_result_msg");
	}

	public void setBusinessCreateTime(java.util.Date businessCreateTime) {
		set("business_create_time", businessCreateTime);
	}
	
	public java.util.Date getBusinessCreateTime() {
		return get("business_create_time");
	}

	public void setBusinessGetTime(java.util.Date businessGetTime) {
		set("business_get_time", businessGetTime);
	}
	
	public java.util.Date getBusinessGetTime() {
		return get("business_get_time");
	}

	public void setBusnessSuccessTime(java.util.Date busnessSuccessTime) {
		set("busness_success_time", busnessSuccessTime);
	}
	
	public java.util.Date getBusnessSuccessTime() {
		return get("busness_success_time");
	}

}
